name: run tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.6.7' #lts
          - '1' #latest stable version
          - '1.9.0-beta3' #latest pre-release version
        julia-arch: [x86, x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        experimental: [false]
        include:
          - julia-version: nightly
            julia-arch: x86
            os: ubuntu-latest
            experimental: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Run Tests
        uses: julia-actions/julia-runtest@latest
